# docker-compose.yml
version: "3.8"

services:
  # Service for the PostgreSQL database
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rails_user -d myapp_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service for Typesense search engine
  typesense:
    image: typesense/typesense:31.0.rc10
    volumes:
      - typesense_data:/data
    environment:
      TYPESENSE_API_KEY: "Ksjdh98238djJHhds82HSDjhj2"
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_LISTEN_PORT: "8108"
      TYPESENSE_ENABLE_CORS: "true"
    ports:
      - "8108:8108"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:8108/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  typesense_data:
  bundle_cache:
