# config/database.yml
default: &default
    adapter: postgresql # Define o adaptador do banco de dados como PostgreSQL
    encoding: unicode # Define a codificação do banco de dados
    # O host é o nome do serviço do banco de dados no docker-compose.yml, que é 'db'
    # Usamos ENV.fetch para pegar a variável de ambiente DATABASE_URL, se definida,
    # caso contrário, usamos 'db' como fallback.
    host: <%= ENV.fetch("DATABASE_URL") { "172.18.0.1" } %>
    port: 5432 # A porta padrão do PostgreSQL
    # O nome de usuário é pego da variável de ambiente POSTGRES_USER do Docker Compose
    username: <%= ENV.fetch("POSTGRES_USER") { "rails_user" } %>
    # A senha é pego da variável de ambiente POSTGRES_PASSWORD do Docker Compose
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # Número de conexões no pool

development:
    <<: *default # Herda todas as configurações do bloco 'default'
    database:
        myapp_development # Nome do banco de dados para o ambiente de desenvolvimento,
        # que corresponde a POSTGRES_DB no docker-compose.yml

test:
    <<: *default
    database: myapp_test # Nome do banco de dados para o ambiente de teste

production:
    <<: *default
    database: myapp_production
    username: <%= ENV.fetch("POSTGRES_USER") { "myapp" } %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") { ENV["MYAPP_DATABASE_PASSWORD"] } %>
    # Em produção, é comum usar uma variável de ambiente diferente para a senha
    # e, opcionalmente, uma URL completa do banco de dados.
    # url: <%= ENV['DATABASE_URL'] %>
